version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price_tracker_db
    ports:
      - "5432:5432"
    restart: always

  bot:
    build: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8443:8443"
    restart: always
